version: '3'

services:
  mongodb-orion-demo:
    container_name: mongodb-orion-demo
    image: mongo:3.4
    expose:
        - "27017"
    command: --nojournal --smallfiles

  mongodb-idas-demo:
    container_name: mongodb-idas-demo
    image: mongo:3.4
    expose:
        - "27017"
    command: --nojournal --smallfiles

  mongodb-comet-demo:
    container_name: mongodb-comet-demo
    image: mongo:3.4
    expose:
        - "27017"
    command: --nojournal

  orion-demo:
    container_name: orion-demo
    image: fiware/orion:1.14.0
    depends_on:
        - mongodb-orion-demo
    expose:
        - "1026"
    ports:
        - "1026:1026"
    command: -dbhost mongodb-orion-demo

  idas-demo:
    container_name: idas-demo
    build:
      context: ./
      dockerfile: idas/Dockerfile
    image: idas/iotagent-json:latest
    depends_on:
        - mongodb-idas-demo
        - mosquitto-demo
    expose:
        - "4041"
    ports:
        - "4041:4041"
    environment:
        - IOTA_MQTT_HOST=mosquitto-demo
        - IOTA_MQTT_PORT=1883
        - IOTA_MQTT_USERNAME=iota
        - IOTA_MQTT_PASSWORD=password

  mosquitto-demo:
    container_name: mosquitto-demo
    build:
      context: ./
      dockerfile: mosquitto/Dockerfile
    image: ool/mosquitto:latest
    expose:
        - "1883"
    ports:
        - "1883:1883"
    environment:
        - IOT_USERNAME=iota
        - IOT_PASS=password

  cygnus-demo:
    container_name: cygnus-demo
    image: fiware/cygnus-ngsi:1.9.0
    depends_on:
        - mongodb-comet-demo
    expose:
        - "5050"
    environment:
        - CYGNUS_MONGO_HOSTS=mongodb-comet-demo:27017

  comet-demo:
    container_name: comet-demo
    image: fiware/sth-comet:2.3.0
    depends_on:
        - mongodb-comet-demo
    expose:
        - "8666"
    ports: 
        - "8666:8666"
    environment:
        - STH_HOST=0.0.0.0
        - DEFAULT_SERVICE=myhome
        - DEFAULT_SERVICE_PATH=/environment  
        - DB_URI=mongodb-comet-demo:27017
        - LOGOPS_LEVEL=DEBUG

#  graph-demo:
#    container_name: graph-demo
#    build:
#      context: ./
#      dockerfile: graph/Dockerfile
#    image: graph/graph:latest
#    depends_on:
#        - comet-demo
#    expose:
#        - "81"
#    ports:
#        - "81:81"
